source 'http://rubygems.org'

gem 'rails', '3.1.1'
gem 'execjs'
gem 'omniauth', '0.3.2'
gem 'therubyracer'
# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

# Łatwiejsze w użyciu formularze
gem 'simple_form'
# albo
# gem 'formtastic'

# Alternatywne dla WEBricka serwery WWW
gem 'thin'
gem 'unicorn'
gem 'rainbows'

# Dopisujemy brakujące gemy (niedopatrzenie autorów Rails 3.1.1)
gem 'sass'
gem 'coffee-script'

group :development do
  # Ładniejsze wypisywanie rekordów na konsoli
  # (zob. konfiguracja irb w ~/.irbrc)
  gem 'wirble'
  gem 'hirb'
  # Bezproblemowe zapełnianie bazy danymi testowymi
  gem 'faker'
  gem 'populator'
end


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
